public import File_System
public import Institute_Inventory
public import Institute_Model
public import Package_Manager
public import Xcode_Scheme
public import Xcode_Workspace

extension Institute.Xcode {
    /// The one generated shared scheme, which is what makes the whole
    /// selection buildable in a single `xcodebuild` invocation.
    ///
    /// Xcode autogenerates a scheme per package product, so a selection of N
    /// packages arrives with hundreds of schemes and no scheme that covers
    /// more than one package — measured: a three-package workspace enumerates
    /// nine, a 199-package one enumerates 1184, and `xcodebuild` accepts
    /// exactly one `-scheme`. Building the selection through those would be N
    /// invocations again, which is the thing being replaced.
    ///
    /// A *shared* scheme may name buildables in more than one container, and
    /// that is the whole mechanism: one scheme, one `BuildActionEntry` per
    /// compilable target across every selected package, `parallelizeBuildables`
    /// on. Xcode merges them into a single dependency graph, schedules it
    /// across all cores, and compiles each shared dependency once rather than
    /// once per package.
    public enum Scheme {}
}

extension Institute.Xcode.Scheme {
    /// The generated scheme's name. Xcode suppresses its autogenerated scheme
    /// for any target a shared scheme already covers, so this name is also
    /// what the covered targets stop being listed under.
    public static let name = "Institute"

    /// One compilable target, and the workspace-relative reference of the
    /// package that declares it.
    public struct Buildable: Sendable, Equatable {
        /// The same relative spelling the workspace document uses —
        /// `../<inventory-derived-reference>`. Never absolute.
        public let reference: Swift.String
        public let target: Swift.String

        public init(reference: Swift.String, target: Swift.String) {
            self.reference = reference
            self.target = target
        }
    }
}

extension Institute.Xcode.Scheme {
    public static func document(
        _ plan: Plan
    ) -> Xcode_Scheme.Xcode.Scheme {
        // Module-qualified: inside `extension Institute.Xcode.Scheme` the
        // unqualified name `Xcode` rebinds to `Institute.Xcode`, so a bare
        // `Xcode.Scheme` would resolve to this very type. Same shadow, and
        // same resolution, as `Institute.Xcode.document(_:)` above.
        Xcode_Scheme.Xcode.Scheme(
            build: plan.buildables.map { buildable in
                .init(
                    reference: .init(
                        blueprint: buildable.target,
                        name: buildable.target,
                        container: "container:\(buildable.reference)"
                    )
                )
            },
            test: plan.testables.map { testable in
                .init(
                    reference: .init(
                        blueprint: testable.target,
                        name: testable.target,
                        container: "container:\(testable.reference)"
                    )
                )
            }
        )
    }

    public static func render(_ plan: Plan) -> Swift.String {
        document(plan).xml
    }

    public static func path(at root: File.Directory) -> File {
        Institute.Xcode.bundle(at: root)[directory: "xcshareddata"][directory: "xcschemes"][
            file: "\(name).xcscheme"
        ]
    }

    public static func contents(at root: File.Directory) -> Swift.String? {
        do throws(Either<File.System.Read.Full.Error, Never>) {
            return try path(at: root).read.full { bytes in
                var storage = [Byte]()
                storage.reserveCapacity(bytes.count)
                for index in bytes.indices {
                    storage.append(bytes[index])
                }
                return Swift.String(decoding: storage, as: Swift.UTF8.self)
            }
        } catch {
            return nil
        }
    }

    /// Whether the scheme on disk is byte-identical to the one the current
    /// manifests render.
    ///
    /// This is the coverage gate, and it has to be a *structural* one. A
    /// `BuildableReference` whose blueprint names no target in its container
    /// is silently dropped: measured on this machine, a scheme carrying one
    /// fabricated entry alongside valid ones exits 0 and prints
    /// `** BUILD SUCCEEDED **` without ever building that package. Only a
    /// scheme in which *every* entry is unmatched fails, with exit 66. So a
    /// name that drifts from its manifest does not fail the build — it
    /// shrinks it, and the shrunken build still looks green.
    ///
    /// Nothing in the build's own output can close that gap either: an
    /// up-to-date target compiles nothing, so "this module is absent from the
    /// log" and "this package was never in the scheme" are the same
    /// observation. The only honest gate is to re-render from the manifests
    /// and compare before building, which is what this is for.
    public static func current(_ plan: Plan, at root: File.Directory) -> Swift.Bool {
        contents(at: root) == render(plan)
    }

    public static func write(
        _ plan: Plan,
        at root: File.Directory
    ) throws(Institute.Error) {
        let bundle = Institute.Xcode.bundle(at: root)
        do throws(Xcode_Scheme.Xcode.Scheme.Error) {
            try document(plan).write(name, to: bundle.description)
        } catch {
            throw .filesystem("cannot write \(path(at: root)): \(error)")
        }
    }
}

extension Institute.Xcode.Scheme {
    /// Every buildable and testable target of every typed workspace member,
    /// in specification order, read from the manifests.
    ///
    /// Read, not guessed, because of the silent-drop behaviour documented on
    /// ``current(_:at:)``. The cost is one `swift package dump-package` per
    /// selected repository, which is the cost `Institute.Doctor` already pays
    /// for its manifest-identity check; this is not a new class of work.
    ///
    /// Test targets populate the shared scheme's real `TestAction`. Plugin,
    /// macro, binary, and system targets are excluded because
    /// they are not blueprints a consumer builds directly — whatever needs
    /// them pulls them in as dependencies of a target that is listed.
    ///
    /// Every specified member must have a readable `Package.swift`; absence or
    /// failed evaluation is an error, never an omission. The final structural
    /// preflight proves a bijection between member containers and scheme
    /// containers, exact V3 target coverage, and a nonempty `TestAction`.
    public static func plan(
        for specification: Institute.Workspace.Specification,
        at root: Institute.Root,
        packages: Package.Manager = .init()
    ) throws(Institute.Error) -> Plan {
        var buildables = [Buildable]()
        var testables = [Testable]()
        for member in specification.members {
            let directory = try directory(for: member, at: root)
            guard directory[file: "Package.swift"].stat.isFile else {
                throw .configuration("workspace member has no Package.swift: \(member.location)")
            }
            let evaluation: Package.Manifest.Evaluation
            do throws(Package.Manager.Error) {
                evaluation = try packages.evaluation(at: directory.description)
            } catch {
                throw .configuration(
                    "cannot evaluate the manifest at \(directory): \(error)"
                )
            }
            guard let location = Xcode_Workspace.Xcode.Workspace.Location(
                rawValue: member.location
            ) else {
                throw .configuration("invalid workspace member location: \(member.location)")
            }
            let reference = location.path
            for target in evaluation.targets {
                // Switched inline rather than through a helper taking a
                // `Target.Kind`: naming that type here would resolve through
                // the enclosing `Institute` scopes first, and an exhaustive
                // switch makes a newly added kind a compile error rather than
                // a target that silently stops being built.
                switch target.kind {
                case .regular, .executable:
                    buildables.append(.init(reference: reference, target: target.name.underlying))

                case .test:
                    testables.append(.init(reference: reference, target: target.name.underlying))

                case .plugin, .binary, .system, .macro:
                    continue
                }
            }
        }
        let plan = Plan(buildables: buildables, testables: testables)
        try preflight(plan, specification: specification)
        return plan
    }

    private static func directory(
        for member: Institute.Workspace.Member,
        at root: Institute.Root
    ) throws(Institute.Error) -> File.Directory {
        guard let location = Xcode_Workspace.Xcode.Workspace.Location(rawValue: member.location),
            location.scheme == .group || location.scheme == .container,
            let relative = try? File.Path(location.path)
        else { throw .configuration("invalid workspace member location: \(member.location)") }
        return File.Directory(root.checkout.path / relative)
    }

    private static func preflight(
        _ plan: Plan,
        specification: Institute.Workspace.Specification
    ) throws(Institute.Error) {
        let specified = Set(specification.members.compactMap {
            Xcode_Workspace.Xcode.Workspace.Location(rawValue: $0.location)?.path
        })
        let containers = Set(plan.buildables.map(\.reference) + plan.testables.map(\.reference))
        guard specified == containers else {
            let absent = specified.subtracting(containers).sorted().joined(separator: ", ")
            let extra = containers.subtracting(specified).sorted().joined(separator: ", ")
            throw .configuration(
                "workspace/scheme container mismatch; absent: [\(absent)]; extra: [\(extra)]"
            )
        }
        guard !plan.testables.isEmpty else {
            throw .configuration("Institute scheme has no testables")
        }
        let buildKeys = plan.buildables.map { $0.reference + "\u{0}" + $0.target }
        let testKeys = plan.testables.map { $0.reference + "\u{0}" + $0.target }
        guard Set(buildKeys).count == buildKeys.count,
            Set(testKeys).count == testKeys.count
        else { throw .configuration("Institute scheme contains duplicate targets") }

        let targets = Set(plan.buildables.map(\.target) + plan.testables.map(\.target))
        let missing = expectedTargets.subtracting(targets)
        guard missing.isEmpty else {
            throw .configuration(
                "Institute scheme omits V3 targets: \(missing.sorted().joined(separator: ", "))"
            )
        }
    }

    private static let expectedTargets: Set<Swift.String> = [
        "Source Measurement",
        "Source Profile",
        "Source Execution",
        "Source Report",
        "Source Repair",
        "Institute Linter Rule Manifest",
        "Institute Continuous Integration Source",
        "Institute Source Workspace",
        "Institute Source Profile",
        "Institute Source",
        "Institute Application Source",
        "Institute Application Source Tests",
    ]
}
