public import Async_Fanout
public import File_System
public import Institute_Inventory
public import Institute_Model
public import Package_Manager
internal import Source_Measurement
public import Xcode_Scheme
public import Xcode_Workspace

extension Institute.Xcode {
    /// The one generated shared scheme, which is what makes the whole
    /// selection buildable in a single `xcodebuild` invocation.
    ///
    /// Xcode autogenerates a scheme per package product, so a selection of N
    /// packages arrives with hundreds of schemes and no scheme that covers
    /// more than one package — measured: a three-package workspace enumerates
    /// nine, a 199-package one enumerates 1184, and `xcodebuild` accepts
    /// exactly one `-scheme`. Building the selection through those would be N
    /// invocations again, which is the thing being replaced.
    ///
    /// A *shared* scheme may name buildables in more than one container, and
    /// that is the whole mechanism: one scheme, one `BuildActionEntry` per
    /// compilable target across every selected package, `parallelizeBuildables`
    /// on. Xcode merges them into a single dependency graph, schedules it
    /// across all cores, and compiles each shared dependency once rather than
    /// once per package.
    public enum Scheme {}
}

extension Institute.Xcode.Scheme {
    /// The generated scheme's name. Xcode suppresses its autogenerated scheme
    /// for any target a shared scheme already covers, so this name is also
    /// what the covered targets stop being listed under.
    public static let name = "Institute"

    /// One compilable target, and the workspace-relative reference of the
    /// package that declares it.
    public struct Buildable: Sendable, Equatable {
        /// The same relative spelling the workspace document uses —
        /// `../<inventory-derived-reference>`. Never absolute.
        public let reference: Swift.String
        public let target: Swift.String

        public init(reference: Swift.String, target: Swift.String) {
            self.reference = reference
            self.target = target
        }
    }
}

extension Institute.Xcode.Scheme {
    public static func document(
        _ plan: Plan
    ) -> Xcode_Scheme.Xcode.Scheme {
        // Module-qualified: inside `extension Institute.Xcode.Scheme` the
        // unqualified name `Xcode` rebinds to `Institute.Xcode`, so a bare
        // `Xcode.Scheme` would resolve to this very type. Same shadow, and
        // same resolution, as `Institute.Xcode.document(_:)` above.
        Xcode_Scheme.Xcode.Scheme(
            build: plan.buildables.map { buildable in
                .init(
                    reference: .init(
                        blueprint: buildable.target,
                        name: buildable.target,
                        container: "container:\(buildable.reference)"
                    )
                )
            },
            test: plan.testables.map { testable in
                .init(
                    reference: .init(
                        blueprint: testable.target,
                        name: testable.target,
                        container: "container:\(testable.reference)"
                    )
                )
            }
        )
    }

    public static func render(_ plan: Plan) -> Swift.String {
        document(plan).xml
    }

    public static func path(at root: File.Directory) -> File {
        path(in: Institute.Xcode.bundle(at: root))
    }

    public static func path(in bundle: File.Directory) -> File {
        bundle[directory: "xcshareddata"][directory: "xcschemes"][
            file: "\(name).xcscheme"
        ]
    }

    public static func contents(at root: File.Directory) -> Swift.String? {
        contents(in: Institute.Xcode.bundle(at: root))
    }

    public static func contents(in bundle: File.Directory) -> Swift.String? {
        do throws(Either<File.System.Read.Full.Error, Never>) {
            return try path(in: bundle).read.full { bytes in
                var storage = [Byte]()
                storage.reserveCapacity(bytes.count)
                for index in bytes.indices {
                    storage.append(bytes[index])
                }
                return Swift.String(decoding: storage, as: Swift.UTF8.self)
            }
        } catch {
            return nil
        }
    }

    /// Whether the scheme on disk is byte-identical to the one the current
    /// manifests render.
    ///
    /// This is the coverage gate, and it has to be a *structural* one. A
    /// `BuildableReference` whose blueprint names no target in its container
    /// is silently dropped: measured on this machine, a scheme carrying one
    /// fabricated entry alongside valid ones exits 0 and prints
    /// `** BUILD SUCCEEDED **` without ever building that package. Only a
    /// scheme in which *every* entry is unmatched fails, with exit 66. So a
    /// name that drifts from its manifest does not fail the build — it
    /// shrinks it, and the shrunken build still looks green.
    ///
    /// Nothing in the build's own output can close that gap either: an
    /// up-to-date target compiles nothing, so "this module is absent from the
    /// log" and "this package was never in the scheme" are the same
    /// observation. The only honest gate is to re-render from the manifests
    /// and compare before building, which is what this is for.
    public static func current(_ plan: Plan, at root: File.Directory) -> Swift.Bool {
        current(plan, in: Institute.Xcode.bundle(at: root))
    }

    public static func current(_ plan: Plan, in bundle: File.Directory) -> Swift.Bool {
        contents(in: bundle) == render(plan)
    }

    public static func write(
        _ plan: Plan,
        at root: File.Directory
    ) throws(Institute.Error) {
        try write(plan, to: Institute.Xcode.bundle(at: root))
    }

    public static func write(
        _ plan: Plan,
        to bundle: File.Directory
    ) throws(Institute.Error) {
        do throws(Xcode_Scheme.Xcode.Scheme.Error) {
            try document(plan).write(name, to: bundle.description)
        } catch {
            throw .filesystem("cannot write \(path(in: bundle)): \(error)")
        }
    }
}

extension Institute.Xcode.Scheme {
    /// Every buildable and testable target of every typed workspace member,
    /// in specification order, read from the manifests.
    ///
    /// Read, not guessed, because of the silent-drop behaviour documented on
    /// ``current(_:at:)``. The cost is one `swift package dump-package` per
    /// selected repository, which is the cost `Institute.Doctor` already pays
    /// for its manifest-identity check; this is not a new class of work.
    ///
    /// Test targets populate the shared scheme's real `TestAction`. Plugin,
    /// macro, binary, and system targets are excluded because
    /// they are not blueprints a consumer builds directly — whatever needs
    /// them pulls them in as dependencies of a target that is listed.
    ///
    /// Every specified member must have a readable `Package.swift`; absence or
    /// failed evaluation is an error, never an omission. The final structural
    /// preflight proves a bijection between member containers and scheme
    /// containers, exact V3 target coverage, and a nonempty `TestAction`.
    public static func plan(
        for specification: Institute.Workspace.Specification,
        at root: Institute.Root,
        packages: Package.Manager = .init(),
        fanout: Async.Fanout = .init(jobs: 32),
        timeout: Swift.Duration = .seconds(120)
    ) async throws(Institute.Error) -> Plan {
        let catalog = try await Institute.Xcode.Acquisition.acquire(
            specification,
            at: root,
            packages: packages,
            fanout: fanout,
            timeout: timeout
        )
        return try plan(for: specification, catalog: catalog)
    }

    /// Pure scheme planning from a complete, manifest- and toolchain-bound catalog.
    public static func plan(
        for specification: Institute.Workspace.Specification,
        catalog: Institute.Xcode.Catalog
    ) throws(Institute.Error) -> Plan {
        guard catalog.entries.map(\.member) == specification.members else {
            throw .configuration("target catalog does not exactly match workspace specification")
        }
        guard Set(catalog.entries.map(\.toolchain)).count == 1,
            catalog.entries.allSatisfy({ $0.manifest.count == 64 && $0.toolchain.count == 64 })
        else {
            throw .configuration("target catalog is not bound to exact manifests and one toolchain")
        }
        for entry in catalog.entries {
            let paths = entry.sources.map(\.path)
            guard paths.contains("Package.swift"),
                Set(paths).count == paths.count,
                entry.sources.allSatisfy({ $0.digest.hex.count == 64 })
            else {
                throw .configuration(
                    "target catalog is not bound to exact source/package inputs at "
                        + entry.reference
                )
            }
        }

        var buildables = [Buildable]()
        var testables = [Testable]()
        for entry in catalog.entries {
            guard
                let location = Xcode_Workspace.Xcode.Workspace.Location(
                    rawValue: entry.member.location
                ), location.path == entry.reference
            else {
                throw .configuration(
                    "target catalog location mismatch for \(entry.member.location): \(entry.reference)"
                )
            }
            for target in entry.targets {
                switch target.kind {
                case .regular, .executable:
                    buildables.append(
                        .init(reference: entry.reference, target: target.name.underlying))
                case .test:
                    testables.append(
                        .init(reference: entry.reference, target: target.name.underlying))
                case .plugin, .binary, .system, .macro:
                    continue
                }
            }
        }
        let result = Plan(buildables: buildables, testables: testables)
        try preflight(result, specification: specification, catalog: catalog)
        return result
    }

    private static func preflight(
        _ plan: Plan,
        specification: Institute.Workspace.Specification,
        catalog: Institute.Xcode.Catalog
    ) throws(Institute.Error) {
        let specified = Set(
            specification.members.compactMap {
                Xcode_Workspace.Xcode.Workspace.Location(rawValue: $0.location)?.path
            })
        let containers = Set(plan.buildables.map(\.reference) + plan.testables.map(\.reference))
        guard specified == containers else {
            let absent = specified.subtracting(containers).sorted().joined(separator: ", ")
            let extra = containers.subtracting(specified).sorted().joined(separator: ", ")
            throw .configuration(
                "workspace/scheme container mismatch; absent: [\(absent)]; extra: [\(extra)]"
            )
        }
        guard !plan.testables.isEmpty else {
            let buildables = plan.buildables
                .map { "\($0.reference):\($0.target)" }
                .joined(separator: ", ")
            throw .configuration(
                "Institute scheme evaluated buildables [\(buildables)] but has no testables"
            )
        }
        let buildKeys = plan.buildables.map { $0.reference + "\u{0}" + $0.target }
        let testKeys = plan.testables.map { $0.reference + "\u{0}" + $0.target }
        guard Set(buildKeys).count == buildKeys.count,
            Set(testKeys).count == testKeys.count
        else { throw .configuration("Institute scheme contains duplicate targets") }

        for entry in catalog.entries {
            guard case .control(let control) = entry.member.role else { continue }
            let actualBuildables = Set(
                entry.targets.compactMap { target -> Swift.String? in
                    switch target.kind {
                    case .regular, .executable: target.name.underlying
                    case .test, .plugin, .binary, .system, .macro: nil
                    }
                })
            let actualTestables = Set(
                entry.targets.compactMap { target -> Swift.String? in
                    switch target.kind {
                    case .test: target.name.underlying
                    case .regular, .executable, .plugin, .binary, .system, .macro: nil
                    }
                })
            let expected = exactTargets(for: control)
            guard actualBuildables == expected.buildables,
                actualTestables == expected.testables
            else {
                let missingBuildables = expected.buildables.subtracting(actualBuildables).sorted()
                let extraBuildables = actualBuildables.subtracting(expected.buildables).sorted()
                let missingTestables = expected.testables.subtracting(actualTestables).sorted()
                let extraTestables = actualTestables.subtracting(expected.testables).sorted()
                throw .configuration(
                    "control target mismatch for \(control.rawValue) at \(entry.reference); "
                        + "missing buildables: \(missingBuildables); extra buildables: \(extraBuildables); "
                        + "missing testables: \(missingTestables); extra testables: \(extraTestables)"
                )
            }
        }

        let targets = Set(plan.buildables.map(\.target) + plan.testables.map(\.target))
        let missing = expectedTargets(for: specification).subtracting(targets)
        guard missing.isEmpty else {
            throw .configuration(
                "Institute scheme omits V3 targets: \(missing.sorted().joined(separator: ", "))"
            )
        }
    }

    private static func expectedTargets(
        for specification: Institute.Workspace.Specification
    ) -> Set<Swift.String> {
        var targets = subjectTargets
        for member in specification.members {
            guard case .control(let control) = member.role else { continue }
            let expected = exactTargets(for: control)
            targets.formUnion(expected.buildables)
            targets.formUnion(expected.testables)
        }
        return targets
    }

    private static let subjectTargets: Set<Swift.String> = [
        "Source Measurement",
        "Source Profile",
        "Source Execution",
        "Source Report",
        "Source Repair",
    ]

    private static func exactTargets(
        for control: Institute.Workspace.Control
    ) -> (buildables: Set<Swift.String>, testables: Set<Swift.String>) {
        switch control {
        case .institute:
            (
                buildables: [
                    "Institute Build Coordinator", "Institute CI Canon", "Institute CI Contract",
                    "Institute CI Inventory", "Institute CI Model", "Institute CI Validation",
                    "Institute CI Workflow", "Institute Conversion", "Institute Dependency",
                    "Institute Development", "Institute Doctor", "Institute Instruments",
                    "Institute Inventory", "Institute Lint", "Institute Model",
                    "Institute Pages", "Institute Repository Policy", "Institute Source",
                    "Institute Source Policy", "Institute Source Profile",
                    "Institute Source Workspace",
                ],
                testables: [
                    "Institute CI Canon Tests", "Institute CI Inventory Tests",
                    "Institute CI Model Tests", "Institute CI Validation Tests",
                    "Institute CI Workflow Tests", "Institute Development Tests",
                    "Institute Instruments Tests", "Institute Source Policy Tests",
                    "Institute Tests",
                ]
            )
        case .application:
            (
                buildables: [
                    "Institute Application", "Institute CI Application",
                    "Institute Application CLI", "Institute Certification Application",
                    "Institute Coherence Application", "Institute Composition Application",
                    "Institute Context Application", "Institute Conversion Application",
                    "Institute Dependency Application", "Institute Doctor Application",
                    "Institute GitHub Application", "Institute Inventory Application",
                    "Institute Lint Application", "Institute Navigation Application",
                    "Institute Package Application", "Institute Repository Application",
                    "Institute Source Application", "Institute Verification Application",
                    "Institute Workspace Application", "Institute Architecture CLI",
                    "Institute Architecture Candidates", "Institute Architecture Facts",
                    "Institute Architecture Graph", "Institute Architecture Index",
                    "Institute Architecture Migration", "Institute Architecture Model",
                    "Institute Architecture Validation", "Institute GitHub",
                ],
                testables: [
                    "Institute CI Application Tests", "Institute Repository Application Tests",
                    "Institute Source Application Tests", "Institute Application Tests",
                    "Institute Architecture Tests",
                ]
            )
        case .continuousIntegration:
            (
                buildables: ["Institute Continuous Integration Source"],
                testables: []
            )
        case .linter:
            (buildables: ["runner"], testables: [])
        }
    }
}
