internal import Byte
public import Institute_Model
public import Process

extension Institute.Inventory {
    /// Process transport for authenticated read-only GitHub maintenance.
    ///
    /// ## This is a deliberate stopgap, not an architecture choice
    ///
    /// This routes requests through the `gh` CLI. It is a Swift transport
    /// adapter over the `Process` product already in this manifest — not shell
    /// automation, and nothing it produces is hand-maintained: the inventory it
    /// feeds is regenerated by command and byte-compared before any write.
    ///
    /// The typed GitHub clients remain transport-agnostic closures. Replacing
    /// this stopgap therefore changes only ``Institute/Inventory/client(_:)``;
    /// discovery, eligibility, exclusion, merge, writer, and inventory format
    /// remain unaffected.
    ///
    /// ## Requirement this imposes
    ///
    /// **`institute inventory regenerate` and `institute dependencies` require
    /// the `gh` CLI, authenticated, on the machine that runs them.** The
    /// credential-free `institute inventory` register and other contributor
    /// commands are unaffected. This is acceptable for read-only maintenance
    /// instrumentation and is *not* library-grade transport.
    public enum Transport {}
}

extension Institute.Inventory.Transport {
    public enum Error: Swift.Error, Equatable, Sendable {
        /// The `gh` process could not be executed at all.
        case spawn(Swift.String)
        /// `gh` ran but exited non-zero, or was signalled.
        case exit(Swift.String)
        /// `gh` succeeded but its output was not a parseable HTTP message.
        case malformed(Swift.String)
    }
}

extension Institute.Inventory.Transport {
    /// A transport that issues each request through `gh api -i`.
    ///
    /// `-i` is required, not cosmetic: response headers carry the RFC 8288
    /// `Link` field, and pagination is driven from `rel="next"`. Without the
    /// headers, discovery silently stops after the first page — which for
    /// `swift-primitives` alone would under-report by roughly half.
    ///
    /// `gh` supplies its own credential, so any `Authorization` the caller set
    /// is dropped rather than forwarded; forwarding it would either be
    /// overridden or conflict.
    public static func githubCLI(
        _ request: [Swift.String]
    ) async throws(Error) -> Response {
        let arguments = ["gh", "api", "-i", "--method", "GET"] + request
        let output: Process.Output
        do throws(Process.Error) {
            output = try Process.Spawn.run(
                .init(
                    executable: "/usr/bin/env",
                    arguments: arguments,
                    stdout: .pipe,
                    stderr: .pipe
                )
            )
        } catch {
            throw .spawn("cannot execute gh: \(error)")
        }

        guard case .exited(let code) = output.status else {
            throw .exit("gh did not exit normally: \(output.status)")
        }
        let stdout = output.stdout ?? []
        guard code == 0 || !stdout.isEmpty else {
            let message = Swift.String(decoding: output.stderr ?? [], as: Swift.UTF8.self)
            throw .exit("gh exited \(code): \(message)")
        }
        guard !stdout.isEmpty else {
            let message = Swift.String(decoding: output.stderr ?? [], as: Swift.UTF8.self)
            throw .malformed(
                "gh exited \(code) and captured no stdout for `\(arguments.joined(separator: " "))`"
                    + (message.isEmpty ? "" : "; stderr: \(message)")
            )
        }
        return try parse(stdout)
    }
}

extension Institute.Inventory.Transport {
    /// Parses `gh api -i` output: a status line, header fields, a blank line,
    /// then the body.
    ///
    /// Line endings are treated as CRLF *or* LF at every boundary. Both occur
    /// here — the wire is CRLF, and a `\r` left on a captured value silently
    /// corrupts a header, which for `Link` would end pagination early.
    ///
    /// **Splitting is done over bytes, deliberately, and must stay that way.**
    /// In Swift `"\r\n"` is a *single* `Character` — one grapheme cluster — so
    /// `String.split(separator: "\n")` does not split CRLF at all. A
    /// `Character`-based parser therefore returns the entire response as one
    /// "line", finds no blank separator, and yields an **empty body**, which
    /// reaches the caller as "empty input" from its JSON decoder and names
    /// neither gh nor this transport. That bug was written here and caught by
    /// the CRLF test; splitting on the newline *byte* is what avoids it.
    internal static func parse(_ bytes: [UInt8]) throws(Error) -> Response {
        var lines: [Swift.String] = []
        var current: [UInt8] = []
        for byte in bytes {
            if byte == 0x0A {  // LF
                if current.last == 0x0D { current.removeLast() }  // strip CR
                lines.append(Swift.String(decoding: current, as: Swift.UTF8.self))
                current.removeAll(keepingCapacity: true)
            } else {
                current.append(byte)
            }
        }
        if !current.isEmpty {
            if current.last == 0x0D { current.removeLast() }
            lines.append(Swift.String(decoding: current, as: Swift.UTF8.self))
        }

        guard let statusLine = lines.first, !statusLine.isEmpty else {
            throw .malformed("gh produced no status line")
        }
        lines.removeFirst()

        // "HTTP/2.0 200 OK" — take the second whitespace-separated field.
        let statusFields = statusLine.split(separator: " ", omittingEmptySubsequences: true)
        guard
            statusFields.count >= 2,
            let code = Swift.Int(statusFields[1])
        else {
            throw .malformed("cannot read a status code from \(statusLine)")
        }
        var fields: [Swift.String: Swift.String] = [:]
        var bodyIndex = lines.count
        for (index, line) in lines.enumerated() {
            if line.isEmpty {
                bodyIndex = index + 1
                break
            }
            guard let separator = line.firstIndex(of: ":") else {
                throw .malformed("cannot read a header field from \(line)")
            }
            let name = Swift.String(line[line.startIndex..<separator])
            let value = Swift.String(line[line.index(after: separator)...])
                .trimmingLeadingSpaces()
            fields[name.lowercased()] = value
        }

        let body = lines[bodyIndex...].joined(separator: "\n")
        return .init(status: code, headers: fields, body: body.isEmpty ? nil : [Byte](body.utf8))
    }
}

extension Swift.String {
    fileprivate func trimmingLeadingSpaces() -> Self {
        var result = Substring(self)
        while result.first == " " || result.first == "\t" {
            result = result.dropFirst()
        }
        return Self(result)
    }
}
